### ISSUE TITLE
Stack Overflow Carrers

### ISSUE THREAD

**Issue by vv221** [ErwannFace/php_challenge2_portfolio#1]
You ask us in this challenge to create and link a Stack Overflow Carrers account, but from what I can see this kind of service is dedicated to employers, not candidates.
So what is the purpose of such an account in our situation?

**Comment by ErwannFace** [comment]
Hi vv221,

Indeed the mentioned link was erroneous. In order to have a developer account, you should create an account as a simple stack overflow user and not in the career section as it is for recruiters.
The link has been updated in the main repository.

Having an account in stack overflow can be a major asset if used.
Displaying once again your skills, therefore interesting in a portfolio.
